name: toolbox
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  receive_sharing_intent: ^1.8.0
  cupertino_icons: ^1.0.6
  go_router: ^14.2.1
  sqflite: ^2.3.3+1
  path: ^1.9.0
  http: ^1.2.2
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
